version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: postgres-container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

  app:
    build: .
    image: blog-image
    container_name: blog-container
    ports:
      - "8087:8087"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
    # volumes:
    #   - ./item:/app/item
    working_dir: /app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:

#services:
#  db:
#    image: mysql:latest
#    container_name: mysql-container
#    ports:
#      - "3308:3306"
#    environment:
#      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
#      MYSQL_DATABASE: ${DB_NAME}
#    volumes:
#      - mysql-data:/var/lib/mysql
#
#  app:
#    build: .
#    image: blog-image
#    container_name: blog-container
#    ports:
#      - "8087:8087"
#    depends_on:
#      - db
#    environment:
#      SPRING_DATASOURCE_URL: ${DB_URL}
#      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
#      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
#    volumes:
#      - ./item:/app/item
#    working_dir: /app
#
#volumes:
#  mysql-data: