services:
  db:
    image: mysql:latest
    container_name: mysql-container
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB_NAME}
    volumes:
      - mysql-data:/var/lib/mysql

  app:
    build: .
    image: blog-image
    container_name: blog-container
    ports:
      - "8087:8087"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: ${DB_URL}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./item:/app/item
    working_dir: /app

volumes:
  mysql-data: